FROM rustlang/rust:nightly as builder
WORKDIR /usr/src/node
COPY . .
RUN cargo build --release -p node

FROM debian:bookworm-slim
COPY --from=builder /usr/src/node/target/release/node /usr/local/bin/node
RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*

CMD ["node"]