[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
bincode = { workspace = true }
futures = { workspace = true }
asynchronous-codec = "0.7.0"
